#pragma once
// Generated by `npm run export:cpp` from lib/ledLayout.ts. Do not edit by hand.
//
// LED layout of the bedroom clock for FastLED. 4 7-segment panels are chained on one data line (DOUT of a panel to DIN of the next); digit 0 is the panel
// next to the controller (hour tens), digit 3 the last (minute units). A panel has 7 segments of 10 LEDs, 70 per panel. The LEDs of a segment are
// consecutive, so a whole segment is switched with one fill_solid(). Segments are named a..g (a = top, b = upper right, c = lower right, d = bottom,
// e = lower left, f = upper left, g = middle); their order in the data chain is different (position, direction of the LED order inside the segment):
//   0: f  up
//   1: a  right
//   2: b  down
//   3: c  down
//   4: d  left
//   5: e  up
//   6: g  right
//
//   CRGB leds[SevenSeg::NUM_LEDS];
//   SevenSeg::setDigit(leds, 2, 7, CRGB::White);               // digit 2 shows a 7
//   SevenSeg::setSegment(leds, 0, SevenSeg::SEG_G, CRGB::Red);  // just the middle bar of digit 0
#include <FastLED.h>
#include <stdint.h>

namespace SevenSeg {

constexpr uint8_t NUM_DIGITS = 4;
constexpr uint8_t SEGMENTS_PER_DIGIT = 7;
constexpr uint8_t LEDS_PER_SEGMENT = 10;
constexpr uint16_t LEDS_PER_DIGIT = 70;
constexpr uint16_t NUM_LEDS = 280;

// Segment letters; the value is the bit in DIGIT_MASK (bit 0 = a ... bit 6 = g).
enum Segment : uint8_t { SEG_A, SEG_B, SEG_C, SEG_D, SEG_E, SEG_F, SEG_G };

// Position of segment a..g in the data chain of one panel.
constexpr uint8_t CHAIN_INDEX[SEGMENTS_PER_DIGIT] = { 1, 2, 3, 4, 5, 0, 6 };

// Lit segments for the digits 0..9, bit 0 = a ... bit 6 = g.
constexpr uint8_t DIGIT_MASK[10] = {
  0x3F, // 0: abcdef  (g..a = 0111111)
  0x06, // 1: bc  (g..a = 0000110)
  0x5B, // 2: abdeg  (g..a = 1011011)
  0x4F, // 3: abcdg  (g..a = 1001111)
  0x66, // 4: bcfg  (g..a = 1100110)
  0x6D, // 5: acdfg  (g..a = 1101101)
  0x7D, // 6: acdefg  (g..a = 1111101)
  0x07, // 7: abc  (g..a = 0000111)
  0x7F, // 8: abcdefg  (g..a = 1111111)
  0x6F  // 9: abcdfg  (g..a = 1101111)
};

// Index of the first LED of a segment (digit 0..3); the segment is [firstLed, firstLed + LEDS_PER_SEGMENT).
constexpr uint16_t firstLed(uint8_t digit, Segment segment) { return digit * LEDS_PER_DIGIT + CHAIN_INDEX[segment] * LEDS_PER_SEGMENT; }

// All 10 LEDs of one segment to one colour (CRGB::Black = off).
inline void setSegment(CRGB* leds, uint8_t digit, Segment segment, const CRGB& color) { fill_solid(leds + firstLed(digit, segment), LEDS_PER_SEGMENT, color); }

// Shows value 0..9 on a digit: the lit segments get `on`, the others `off`. Any other value blanks the digit.
inline void setDigit(CRGB* leds, uint8_t digit, uint8_t value, const CRGB& on, const CRGB& off = CRGB::Black) {
  const uint8_t mask = value < 10 ? DIGIT_MASK[value] : 0;
  for (uint8_t s = 0; s < SEGMENTS_PER_DIGIT; s++) setSegment(leds, digit, static_cast<Segment>(s), (mask >> s) & 1 ? on : off);
}

}  // namespace SevenSeg
