import { DIGIT_SEGMENTS, LEDS_PER_DIGIT, LEDS_PER_SEGMENT, NUM_DIGITS, SEGMENT_DIRECTION, SEGMENT_ORDER, type SegmentId } from '../lib/ledLayout';

// Prints cpp/SevenSegLayout.h (FastLED helper) to stdout: `npm run export:cpp` (needs Bun on PATH, like tsci). Layout source: lib/ledLayout.ts.
const LETTERS: SegmentId[] = ['a', 'b', 'c', 'd', 'e', 'f', 'g']; // enum / bit order in the C++ code
const bits = (segments: readonly SegmentId[]) =>
  [...LETTERS]
    .reverse()
    .map((l) => (segments.includes(l) ? '1' : '0'))
    .join(''); // g..a
const mask = (segments: readonly SegmentId[]) => '0x' + parseInt(bits(segments), 2).toString(16).toUpperCase().padStart(2, '0');
const chainIndex = LETTERS.map((l) => SEGMENT_ORDER.indexOf(l));
const chainTable = SEGMENT_ORDER.map((id, i) => `//   ${i}: ${id}  ${SEGMENT_DIRECTION[id]}`).join('\n');
const digitMasks = DIGIT_SEGMENTS.map((segments, d) => `  ${mask(segments)}${d < 9 ? ',' : ' '} // ${d}: ${segments.join('')}  (g..a = ${bits(segments)})`).join('\n');

console.log(`#pragma once
// Generated by \`npm run export:cpp\` from lib/ledLayout.ts. Do not edit by hand.
//
// LED layout of the bedroom clock for FastLED. ${NUM_DIGITS} 7-segment panels are chained on one data line (DOUT of a panel to DIN of the next); digit 0 is the panel
// next to the controller (hour tens), digit ${NUM_DIGITS - 1} the last (minute units). A panel has ${SEGMENT_ORDER.length} segments of ${LEDS_PER_SEGMENT} LEDs, ${LEDS_PER_DIGIT} per panel. The LEDs of a segment are
// consecutive, so a whole segment is switched with one fill_solid(). Segments are named a..g (a = top, b = upper right, c = lower right, d = bottom,
// e = lower left, f = upper left, g = middle); their order in the data chain is different (position, direction of the LED order inside the segment):
${chainTable}
//
//   CRGB leds[SevenSeg::NUM_LEDS];
//   SevenSeg::setDigit(leds, 2, 7, CRGB::White);               // digit 2 shows a 7
//   SevenSeg::setSegment(leds, 0, SevenSeg::SEG_G, CRGB::Red);  // just the middle bar of digit 0
#include <FastLED.h>
#include <stdint.h>

namespace SevenSeg {

constexpr uint8_t NUM_DIGITS = ${NUM_DIGITS};
constexpr uint8_t SEGMENTS_PER_DIGIT = ${SEGMENT_ORDER.length};
constexpr uint8_t LEDS_PER_SEGMENT = ${LEDS_PER_SEGMENT};
constexpr uint16_t LEDS_PER_DIGIT = ${LEDS_PER_DIGIT};
constexpr uint16_t NUM_LEDS = ${NUM_DIGITS * LEDS_PER_DIGIT};

// Segment letters; the value is the bit in DIGIT_MASK (bit 0 = a ... bit 6 = g).
enum Segment : uint8_t { SEG_A, SEG_B, SEG_C, SEG_D, SEG_E, SEG_F, SEG_G };

// Position of segment a..g in the data chain of one panel.
constexpr uint8_t CHAIN_INDEX[SEGMENTS_PER_DIGIT] = { ${chainIndex.join(', ')} };

// Lit segments for the digits 0..9, bit 0 = a ... bit 6 = g.
constexpr uint8_t DIGIT_MASK[10] = {
${digitMasks}
};

// Index of the first LED of a segment (digit 0..${NUM_DIGITS - 1}); the segment is [firstLed, firstLed + LEDS_PER_SEGMENT).
constexpr uint16_t firstLed(uint8_t digit, Segment segment) { return digit * LEDS_PER_DIGIT + CHAIN_INDEX[segment] * LEDS_PER_SEGMENT; }

// All ${LEDS_PER_SEGMENT} LEDs of one segment to one colour (CRGB::Black = off).
inline void setSegment(CRGB* leds, uint8_t digit, Segment segment, const CRGB& color) { fill_solid(leds + firstLed(digit, segment), LEDS_PER_SEGMENT, color); }

// Shows value 0..9 on a digit: the lit segments get \`on\`, the others \`off\`. Any other value blanks the digit.
inline void setDigit(CRGB* leds, uint8_t digit, uint8_t value, const CRGB& on, const CRGB& off = CRGB::Black) {
  const uint8_t mask = value < 10 ? DIGIT_MASK[value] : 0;
  for (uint8_t s = 0; s < SEGMENTS_PER_DIGIT; s++) setSegment(leds, digit, static_cast<Segment>(s), (mask >> s) & 1 ? on : off);
}

}  // namespace SevenSeg`);
